
#General settings
[elementaryores]

	[elementaryores.nether]

		[elementaryores.nether.diamond]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 100
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -8
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.iron]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 8
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -8
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.coal]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 12
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 256
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 60
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.copper]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -8
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.lapis]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 6
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 90
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -8
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.ghast]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 64
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -16
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.nether.emerald]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 32
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 25

	[elementaryores.end]

		[elementaryores.end.diamond]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 32
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -16
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.coal]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 80
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 1
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.copper]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 1
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.ender]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 16
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = -8
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.lapis]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 100
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 1
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.redstone]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 128
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 50
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 50

		[elementaryores.end.emerald]
			#
			# Registered worldgen feature size
			#Range: 0 ~ 64
			size = 4
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			highest = 64
			#
			# Min and max y levels for spawn
			#Range: -4096 ~ 4096
			lowest = 1
			#
			# Spread area
			#Range: 0 ~ 64
			spread = 25

