
#General settings
[elementaryores]

	[elementaryores.nether]

		[elementaryores.nether.diamond]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 2
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 40
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

		[elementaryores.nether.iron]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 8
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 256
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 70

		[elementaryores.nether.lapis]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 4
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 60
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 0

		[elementaryores.nether.emerald]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 2
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 256
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 70

	[elementaryores.end]

		[elementaryores.end.diamond]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 1
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 256
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

		[elementaryores.end.ender]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 10
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 256
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

		[elementaryores.end.lapis]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 2
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 256
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

		[elementaryores.end.redstone]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 4
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 70
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

		[elementaryores.end.emerald]
			#Size of ore veins
			#Range: 0 ~ 64
			size = 4
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			highest = 60
			#Min and max y levels for spawn
			#Range: 0 ~ 256
			lowest = 1

