

mod_id=elementaryores
curse_id=332609
curse_slug=elementary-ores
mod_version=2.1.0
mod_name=elementaryores
mod_group_id=com.lothrazar.elementaryores
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=elementary-ores

flib_version=0.1.0
flib_file=8022223


